version: '3'

networks:
  laravel:

services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    networks:
      - laravel
